# Semgrep Configuration
# This file defines which Semgrep rulesets to use for code analysis.
# See https://semgrep.dev/docs/

rules:
  # Python Security and Best Practices
  - id: python-best-practices
    patterns:
      - pattern-inside: |
          import $MODULE
    languages: [python]
    severity: INFO
    message: Using Semgrep community rulesets for Python analysis

# Use community rulesets (configured in qlty.toml)
# These are pulled automatically by Semgrep:
# - p/python: Python best practices
# - p/security-audit: Security auditing
# - p/owasp-top-ten: OWASP Top 10 vulnerabilities
# - p/django: Django-specific rules (if applicable)

# Custom rules can be added here
# See https://semgrep.dev/docs/writing-rules/overview/
